### ISSUE TITLE
Improve proposal creation

### ISSUE THREAD

**Issue by ignacioVidaurreta** [ignacioVidaurreta/AluProp#84]
### Tasks
- [x] Property for one
    - [x] Allow students to create proposal for one person
- [x] Proposal Creation REVISITED
    - [x] Update frontend of proposals in profile
    - [x] Modify "Create Proposal" button location
    - [x] Link to other user profiles and add a preview of its bio
    - [x] Create a pop-up informing the implications of the action. It will also inform depending the amount of users involved in the proposal, the amount of money per student per month. If creating a proposal for one, it will warn the user of the desition
    - [x] Update frontend of detailed property. Make it more friendly
