### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ignacioVidaurreta** [ignacioVidaurreta/AluProp#85]
### Tasks

- [x] Front end
    - [x] Add notification icon that displays notifications
    - [x] Create popup that shows notifications
    - [x] Redesign navbar
    - [x] Create Notification Manager screen

- [x] Backend
    - [x] Add notifications table to schema
    - [x] Implement NotificationDAO
    - [x] Send notification to user when invited to a proposal --> This notification should redirect to proposal screen to accept or deny the proposal
    - [x] Send notification to Host when a proposal is completed --> This notification should redirect to the proposal screen for the host to approve or deny the proposal
    - [x] Popup should only show unread notifications belonging to the user that's currently logged in.
