### ISSUE TITLE
Update profile

### ISSUE THREAD

**Issue by ignacioVidaurreta** [ignacioVidaurreta/AluProp#87]
### Tasks
- [x] Host should be able to modify its property availability.
- [x] The availability of the property should be seen from the host profile
- [x] Merge branch once hibernate is working.
